language: node_js
node_js:
  - 12.22.1
cache: yarn

# 设置需要监听的分支
branches:
  only:
    - master

# 分为install, script和deploy三个阶段

# 写成install: true可以跳过install
install:
  - yarn install

# 脚本，用来构建或测试
# 同时, script和install执行过程中有差异
# 当script某个command失败，并不会像install那样停下来
# 而是会继续执行其他command，但整个构建过程是失败的
# (莫不是因为script用了并行:sassy_man:)
script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  # 很重要的一个字段，因为我们是需要build后出来的dist文件夹，不能删掉
  skip_cleanup: true
  # 这是从github设置token，放到travis里面当变量
  token: $GITHUB_TOKEN
  # build出来的在dist文件夹下
  local_dir: dist
  # target_branch，travis帮你push的branch名，可以设成githubpage对应的branch
  target_branch: test
  on: 
    branch: master
