language: node_js
node_js:
  - 12.22.1
cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: test
  on: 
    branch: master
