sudo: false
language: node_js
node_js:
  - 12.22.9
cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: test
  on: 
    branch: master
